Amazon_Dashboard/Amazon_WebApp/Amazon_WebApp/Areas/Expenses/Controllers/ExpenseCapturesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AmazonModel.Expenses;

namespace Amazon_WebApp.Areas.Expenses.Controllers
{
    public class ExpenseCapturesController : Controller
    {
        private ExpensesEntities db = new ExpensesEntities();

        // GET: Expenses/ExpenseCaptures
        public ActionResult Index()
        {
            return View(db.ExpenseCaptures.ToList());
        }

        // GET: Expenses/ExpenseCaptures/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExpenseCapture expenseCapture = db.ExpenseCaptures.Find(id);
            if (expenseCapture == null)
            {
                return HttpNotFound();
            }
            return View(expenseCapture);
        }

        // GET: Expenses/ExpenseCaptures/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Expenses/ExpenseCaptures/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ExpenseCaptureId,ExpenseDate,ExpenseAmount,MerchantId,ExpenseCode")] ExpenseCapture expenseCapture)
        {
            if (ModelState.IsValid)
            {
                db.ExpenseCaptures.Add(expenseCapture);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(expenseCapture);
        }

        // GET: Expenses/ExpenseCaptures/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExpenseCapture expenseCapture = db.ExpenseCaptures.Find(id);
            if (expenseCapture == null)
            {
                return HttpNotFound();
            }
            return View(expenseCapture);
        }

        // POST: Expenses/ExpenseCaptures/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ExpenseCaptureId,ExpenseDate,ExpenseAmount,MerchantId,ExpenseCode")] ExpenseCapture expenseCapture)
        {
            if (ModelState.IsValid)
            {
                db.Entry(expenseCapture).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(expenseCapture);
        }

        // GET: Expenses/ExpenseCaptures/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExpenseCapture expenseCapture = db.ExpenseCaptures.Find(id);
            if (expenseCapture == null)
            {
                return HttpNotFound();
            }
            return View(expenseCapture);
        }

        // POST: Expenses/ExpenseCaptures/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ExpenseCapture expenseCapture = db.ExpenseCaptures.Find(id);
            db.ExpenseCaptures.Remove(expenseCapture);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Amazon_Dashboard/Amazon_WebApp/Amazon_WebApp/Areas/Inventory/Controllers/NewInventoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AmazonModel.Inventory;

namespace Amazon_WebApp.Areas.Inventory.Controllers
{
    public class NewInventoriesController : Controller
    {
        private InventoryEntities db = new InventoryEntities();

        // GET: Inventory/NewInventories
        public ActionResult Index()
        {
            return View(db.NewInventories.ToList());
        }

        // GET: Inventory/NewInventories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewInventory newInventory = db.NewInventories.Find(id);
            if (newInventory == null)
            {
                return HttpNotFound();
            }
            return View(newInventory);
        }

        // GET: Inventory/NewInventories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Inventory/NewInventories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PurchaseId,PurchaseDate,InventoryType,QuantityPurchased,Cost,PurchaseReason,PercentagePaid,ItemId,TheSourceId")] NewInventory newInventory)
        {
            if (ModelState.IsValid)
            {
                db.NewInventories.Add(newInventory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(newInventory);
        }

        // GET: Inventory/NewInventories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewInventory newInventory = db.NewInventories.Find(id);
            if (newInventory == null)
            {
                return HttpNotFound();
            }
            return View(newInventory);
        }

        // POST: Inventory/NewInventories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PurchaseId,PurchaseDate,InventoryType,QuantityPurchased,Cost,PurchaseReason,PercentagePaid,ItemId,TheSourceId")] NewInventory newInventory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(newInventory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(newInventory);
        }

        // GET: Inventory/NewInventories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewInventory newInventory = db.NewInventories.Find(id);
            if (newInventory == null)
            {
                return HttpNotFound();
            }
            return View(newInventory);
        }

        // POST: Inventory/NewInventories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NewInventory newInventory = db.NewInventories.Find(id);
            db.NewInventories.Remove(newInventory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Amazon_Dashboard/Amazon_WebApp/Amazon_WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MediaBazaar Dashboard</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MediaBazaar Dashboard", "", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inventory", "Index", "NewInventories", new { @area = "Inventory" }, new { @class = "navbar-brand" })</li>
                    <li>@Html.ActionLink("Expenses", "Index", "ExpenseCaptures", new { @area = "Expenses" }, new { @class = "navbar-brand" })</li>

                    <li>@Html.ActionLink("Reporting", "Index", "Reporting", new { @area = "Reporting" }, new { @class = "navbar-brand" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "navbar-brand" })</li>
                    <li>@Html.ActionLink("Help", "Contact", "Home", new { area = "" }, new { @class = "navbar-brand" })</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MediaBazaar Dashboard</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>